import type { Metadata } from "next";
import { Inter } from "next/font/google";
import WalletContextProvider from "./wallet/WalletContextProvider";
import "./globals.css";
import AppWalletProvider from "./wallet/WalletContextProvider";
import Head from "next/head";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./components/Navbar/Navbar";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* <title>{metadata.title}</title> */}
        {/* <meta name="description" content={metadata.description} /> */}
        <script src="https://terminal.jup.ag/main-v2.js" data-preload></script>
      </Head>
      <body className={inter.className}>
        {" "}
        <AppWalletProvider>
          <Navbar />
          {children}
        </AppWalletProvider>
      </body>
    </html>
  );
}
